# code: language=ansible
---
tenant_name: "automation-demo"
cloud_parameters:
  name: '{{ cloud_name | default("Default-Cloud") }}'

vs_parameters:
  name: "rc-ansible-demo"
  fqdn: "rc-ansible-demo.vs.rc.demo.avi.local"
  ipam_network_subnet:
    subnet:
      ip_addr:
        type: "V4"
        addr: "100.66.66.0"
      mask: 24
  pool_members:
    - ip:
        addr: "100.66.67.201"
        type: "V4"
    - ip:
        addr: "100.66.67.202"
        type: "V4"
    - ip:
        addr: "100.66.67.203"
        type: "V4"
